config {
  type: "table",
  bigquery: {
    partitionBy: "DATE(ts)"
  }
}

SELECT 
  CURRENT_TIMESTAMP() AS TS, 
  100 AS AccountNumber, 
  'ricardop' AS ClientName,
  'HomeLoan' AS AccountType
UNION ALL
SELECT 
  CURRENT_TIMESTAMP() AS TS, 
  101 AS AccountNumber, 
  'nataliap' AS ClientName,
  'HomeLoan' AS AccountType
UNION ALL
SELECT 
  CURRENT_TIMESTAMP() AS TS, 
  102 AS AccountNumber, 
  'julianap' AS ClientName,
  'CarLoan' AS AccountType
